### ISSUE TITLE
Folio side and column available in witness field?

### ISSUE THREAD

**Issue by stenskjaer** [scta/scta-projectfiles#8]
Is it possible to enter information about the side and column of where a item starts?

It would be very useful, and in line with general practice, to be able to write 
``` xml
<hasWitnesses>
  <witness ref="#O">
    <folio>120-va</folio>
  </witness>
</hasWitnesses>
```
Or just the side, indicated like `[number]-[side]` (like with the `pb` element in https://github.com/lombardpress/lombardpress-schema/issues/11), which would the be:
``` xml
<hasWitnesses>
  <witness ref="#O">
    <folio>120-v</folio>
  </witness>
</hasWitnesses>
```

**Comment by jeffreycwitt** [comment]
I agree that this added information is desirable.

But can we take as a starting assumption that if an item appears on a folio-side and no column is mentioned then it appears on both columns. 

Thus, we would only need to indicate that if it starts on column B or ends on column A

```xml
<hasWitnesses>
  <witness ref="#O">
    <folio c="b">120v</folio>
   <folio>121r</folio>
   <folio c="a">121v</folio>
  </witness>
</hasWitnesses>
```

I've been doing the above as a temporary measure for my own sanity. But the "c" gets ignored in any subsequent processing. 

What's the immediate use case for this information? Do you need it for anything? Or do you just want to record it so we don't have to record it again. If the latter, I would just use the "c" attribute, as I have, as a temporary measure. Then we can port this information to whatever finalized schema we come up with.

In general being more explicit is desirable and I would prefer to do this with key=value pairs rather than with string parsing. So someday, we might want to do

```xml
<hasWitnesses>
  <witness ref="#O">
    <folio f="120" s="v" c="b"/>
   <folio f="121" s="r" c="a b"/>
   <folio f="121" s="v" c="a"/>
  </witness>
</hasWitnesses>
```

**Comment by stenskjaer** [comment]
As I use this for question lists, I just want to be able to figure out more accurately where the content starts and ends. Both the suggestion solutions are fine by me. 
I think the solution of key-value pairs is a good idea. Is using a `@f` (or maybe better `@n` in parallel with the `pb`-element?), better than an element-value?

Anyway, I think I will adopt your temporary approach for now.
